# Generated by Django 6.0.3 on 2026-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Global Settings', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='dashboard_backgrounds/')),
            ],
        ),
    ]
