# Generated by Django 6.0.3 on 2026-03-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('preparing', 'Preparing'), ('on_way', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
    ]
