# Generated by Django 6.0.3 on 2026-04-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin')], default=None, max_length=10, null=True),
        ),
    ]
