# Generated by Django 6.0.3 on 2026-03-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Order delivery near you', max_length=200)),
                ('hero_image', models.ImageField(upload_to='landing_pages/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
